"""Removed time field from transport booking model

Revision ID: 684e0531eea2
Revises: 
Create Date: 2024-11-09 14:09:30.741129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684e0531eea2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_outside', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_outside', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
